### PR TITLE
[BUGFIX] cache not clearing reliably when modifying options

### PR DESCRIPTION
**Pull request by joebartels**
I was having hack of a time getting the expected output as I was modifying the option's method, `resolveModuleSource`.

### CODE REVIEW

**Comment by Turbo87** [comment]
could you describe what the actual big was and how exactly you fixed it?

**Comment by joebartels** [comment]
Sure. 
The bug was that when modifying the method, `resolveModuleSource` in my Brocfile - the per file cache key doesn't change.

i.e.,
 `Babel.prototype.cacheKeyProcessString` is expected to return a different value when the Babel options change - however when the *internals* of a method change, the `return` value doesn't vary compared to before the change.

e.g.,
```
var myTree = BabelTranspiler('scripts', {
  modules: 'amdStrict',
  resolveModuleSource(source, filename) {
    // change code in here
  }
});
```
`Babel.prototype.optionsHash` returns the same hash when the *internals* of the method change.
https://github.com/babel/broccoli-babel-transpiler/blob/master/index.js#L105

because `stringify(this.options)` ends up returning the following:
`"{\"modules\":\"amdStrict\"}"`, ignoring that there's even a method.

The fix just loops through each property in `this.options` and does a `toString()` when the value is type function so that methods can be taken into account when building the `optionsHash`.

**Comment by Turbo87** [comment]
okay, that seems reasonable. what's the reason for using `md5-hex` now instead of `crypto`?

**Comment by joebartels** [comment]
Ah. If I remember correctly I first started debugging by comparing the generated hash using a different library and by the time I figured the actual problem I just left it in there. So - no good reason. If you prefer I'll update this PR by putting the native library back and include a test for `optionsHash`

**Comment by Turbo87** [comment]
Yeah that would be awesome, thanks!

**Comment by joebartels** [comment]
@Turbo87 updated

**Comment by Turbo87** [comment]
👍 

unless @stefanpenner has any short-term objections I'll merge this soonish.

**Comment by chadhietala** [comment]
This LGTM

**Pull request merged**
