### PR TITLE
optionally prevent a double AMD compile

### PR DESCRIPTION
**Pull request by kellyselden**
The AmdFunnel in ember-cli has optimizations in it to do as little file IO as possible. https://github.com/ember-cli/ember-cli/blob/bd36eca668f8fab21cc9cdfdaae97ffcdc1de9ee/lib/broccoli/ember-app.js#L1652. As it turns out, these optimizations are not good enough, and early exit doesn't seem possible. I decided to try a different approach, to catch the string right before the compile and prevent it going through a second time. The AmdFunnel code can be removed if this is merged.

cc @twokul

### CODE REVIEW

**Comment by twokul** [comment]
would we want `preventDoubleAmdCompile` to always be on?

**Comment by kellyselden** [comment]
In ember-cli, yes. I didn't want to make any assumptions about any other potential consumers of this lib.

**Comment by kellyselden** [comment]
Added a callback so ember-cli can print the same deprecation warning as it did with AmdFunnel.

**Comment by stefanpenner** [comment]
I believe the work that motivated this change has taken a different direction, closing for now. Let me know if I have closed this in error.

**Pull request closed without merging**
