### PR TITLE
Support disabling parallelism via JOBS=0

### PR DESCRIPTION
**Pull request by stefanpenner**
- [x] flesh out

### CODE REVIEW

**Comment by rwjblue** [comment]
Hmmm, I'm not sure I follow the goal here.  You can already opt-out via `JOBS=1`, are you just saying that `JOBS=0` should also work?

**Comment by rwjblue** [comment]
FWIW, the `process.env.JOBS` value is handled upstream of us in broccoli-persistent-filter itself here: https://github.com/stefanpenner/broccoli-persistent-filter/blob/2c53271700258e914af6108eb6d919b76f039598/index.js#L92

**Comment by stefanpenner** [comment]
> Hmmm, I'm not sure I follow the goal here. You can already opt-out via JOBS=1, are you just saying that JOBS=0 should also work?

in both cases no worker is required

**Comment by stefanpenner** [comment]
> FWIW, the process.env.JOBS value is handled upstream of us in broccoli-persistent-filter itself here: https://github.com/stefanpenner/broccoli-persistent-filter/blob/2c53271700258e914af6108eb6d919b76f039598/index.js#L92

Ah, wil fix

**Pull request merged**
