### PR TITLE
use new build api

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by chadhietala** [comment]
Looks like you may have these linked locally where cauliflower-filter has been migrated to the rebuild API.

**Comment by stefanpenner** [comment]
Yes. That is intentional. This pr is pre-emtive

Sorry should have posted that in the description

**Comment by stefanpenner** [comment]
Yes. That is intentional. This pr is pre-emtive

Sorry should have posted that in the description

**Comment by chadhietala** [comment]
Closing as it now uses broccoli-filter which uses the `build` api.

**Pull request closed without merging**
