### PR TITLE
examples section

### PR DESCRIPTION
**Pull request by givanse**

### CODE REVIEW

**Comment by givanse** [comment]
Let me know if all good :+1: and I'll squash them.

**Comment by arthurvr** [comment]
ping @stefanpenner @sebmck.

Maybe we should try to shorten the place it takes up in the readme a bit but I think some examples can't hurt for people that are new to babel (or to broccoli).

**Comment by givanse** [comment]
Remove the second commit?

**Comment by stefanpenner** [comment]
is it possible for me to get commit on the DEMO repo's, that way i can help maintain them going forward.

**Comment by givanse** [comment]
Yep, done.

**Pull request merged**
