### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by binoculars**
* Remove Node 0.12 (deprecated)
* Use LTS versions of node 4 and 6
* sudo false for container-based infrastructure (runs faster)
* dist trusty (use Ubuntu 14.04)
* Install latest NPM

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you also update `appveyor.yml`?

**Comment by rwjblue** [comment]
Thanks for fixing!

**Comment by binoculars** [comment]
I'd have to look at the docs for appveyor. I haven't used it yet.

**Comment by Turbo87** [comment]
hmm... I'm not sure I agree on those changes. It seems that the trusty image is still in beta (see https://docs.travis-ci.com/user/trusty-ci-environment/). And where is the difference between those Node versions? shouldn't `6` default to the latest 6 LTS?

**Comment by binoculars** [comment]
The trusty image has been in beta for a very long time now. It's based on Ubuntu 14 vs 12, which is all but dead. Not sure why Travis wants to keep the beta label, but it's stable at this point.

See https://github.com/nodejs/LTS for LTS info.

**Pull request merged**
