### PR TITLE
[feature] adds heimdall monitor for logging information helpful for debugging babel process

### PR DESCRIPTION
**Pull request by gabrielcsapo**
I am working on https://github.com/gabrielcsapo/broccoli-inspector and a feature it has is to surface monitor related information to the user to provide information helpful debugging.

This information will surface the following:

Screen Shot 2020-05-10 at 7 58 07 PM

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@Turbo87 would you be able to take a look at this?

**Comment by Turbo87** [comment]
sorry, I have zero context on heimdall. maybe @rwjblue or @stefanpenner have a better idea.

**Comment by stefanpenner** [comment]
released as v7.6.0 🎉

**Comment by fullsailor** [comment]
Hey @gabrielcsapo I'm not certain, but this depends on heimdalljs:  "^0.2.1", but `heimdall.hasMonitor()` was introduced in 0.3.1 (if the tag is right) https://github.com/heimdalljs/heimdalljs-lib/commit/a332fd3dadda31075eace83be7e8ab8645b119cf

Should the package.json be changed to "^0.3.1"?

**Pull request merged**
