### PR TITLE
Allow targetExtesion to be passed in as an option

### PR DESCRIPTION
**Pull request by jeffjo**
I was trying to pass in the targetExtension option and I was getting a `Unknown option: direct.targetExtension` error. This should fix that

### CODE REVIEW

**Comment by stefanpenner** [comment]
@jeffjo sounds good, mind adding a test?

**Comment by jeffjo** [comment]
Better late than never. I added a test and fixed a few nits that I found. PTAL

**Comment by stefanpenner** [comment]
rebase + landed here: https://github.com/babel/broccoli-babel-transpiler/pull/136

**Comment by stefanpenner** [comment]
released as v6.3.0 🎉

**Pull request closed without merging**
