### PR TITLE
Babel 6

### PR DESCRIPTION
**Pull request by shaunc**
The tests needed a bit of tweaking for this. Rename of "sourceMapName" option to "sourceMapTarget" already happened a while ago. I'm not sure how `options.modules` should be treated, so disabled those tests (but would be happy to fix if I knew how). I presume the inline sourcemap content change is benign, but don't know how to test this.

I don't know how you want to move to babel-6 ... if there is something (more than this PR) I can do to help, please ring. :)

### CODE REVIEW

**Comment by shaunc** [comment]
**update**: upstream usage in actual project does pass "modules" ... also inline sourcemap change doesn't seem portable (one CI error; the others were timeouts). I wonder what is different about my environment. npm 3.6? I'm happy to improve this PR -- comments appreciated. (What is "modules" in babel-6 anyway?)

**Comment by shaunc** [comment]
It seems that "modules" option has been replaced by plugins (NB is there a transition guide somewhere?). Now using `transform-es2015-modules-amd` plugin instead of `modules: 'amdStrict'` in named modules tests.

Still presumably have problems with source maps. I wonder if this is because I'm on npm 3.6? Not exactly sure how to debug the difference. Of course, we could loosen up the test so the inline sourcemap string needn't match exactly. Suggestions?

**Comment by ming-codes** [comment]
I'm going to +1 this.

Babel 6's plugin interface changed quite a bit and all the docs have moved over to 6 now.

**Comment by maherbeg** [comment]
Is there anything we can do to get this moving? Is this plugin deprecated? Happy to help however I can!

**Comment by Turbo87** [comment]
@shaunc can I close this in favor of #70?

**Comment by shaunc** [comment]
(closing in favor of #70)

**Pull request closed without merging**
