### PR TITLE
Allow passing in extensions to babelize

### PR DESCRIPTION
**Pull request by jschilli**
The use case here is to limit the performance impact of babel on larger projects and support 'opt-in' semantics.

I've made a similar change in https://github.com/babel/ember-cli-babel but IMO it was not as clean.

named `validExtensions` iso `extensions` to avoid conflict with babel options

```javascript
var app = new EmberApp({
    babel: {
        validExtensions:['es6'],
        compact: false,
        blacklist: ['validation.react']
    },
```

This supports our biggest initial build time issue as documented at https://github.com/ember-cli/ember-cli/issues/3637#issuecomment-85745165

I'm open to alternatives but short of forking ember-cli-babel I can't think of a good one

### CODE REVIEW

**Comment by stefanpenner** [comment]
ya this seems to be missing, can you:

* call it `options.extensions`
* add a test
* short blurb in the readme

**Comment by jschilli** [comment]
hmm, I named it validExtensions b/c babel seemed to accept `extensions` w/o complaint and I didn't want to shadow their option name

I can't find a reference to it in their code so will change

I'll add tests - unfortunately the current tests do not pass (prior to this change - and not super obvious why - I opened #16 to track that)

will have something soon

**Comment by jschilli** [comment]
was chasing test failure in #16 - will get back to cleaning this up.

`options.extensions` won't work - it is a valid babel config option 

https://github.com/babel/babel/blob/master/src/babel/transformation/file.js#L123

I'll resubmit with tests and readme and using `validExtensions` - feel free to suggest an alternative

**Comment by stefanpenner** [comment]
Maybe broccoli extensions or...  Valid is likely also fine

**Comment by jschilli** [comment]
went with `filterExtensions`.

you'll note that brute forced the `basic` test by adding options to babel where there previously were none.

given that babel continues to change and this is a regression there I've opened up an issue with babel (https://github.com/babel/babel/issues/1111) 

The test does exactly what it used to albeit with different (and currently valid) options.

so if this gets released/published with a 4.x.x version number we wont have to make any changes to ember-cli-babel? correct?

Thanks for the feedback

**Comment by stefanpenner** [comment]
> so if this gets released/published with a 4.x.x version number we wont have to make any changes to ember-cli-babel? correct?

correct

**Comment by stefanpenner** [comment]
released as `4.1.0`

**Comment by jschilli** [comment]
awesome - many thanks!

**Pull request merged**
