### PR TITLE
Remove untested `exportModuleMetadata` option.

### PR DESCRIPTION
**Pull request by eventualbuddha**
We can always bring this back if it’s deemed useful.

### CODE REVIEW

**Comment by Turbo87** [comment]
seems fine to me

@stefanpenner @rwjblue any opinions?

**Comment by stefanpenner** [comment]
hmm, I am actually quite close to wanting this again. I would love to bring it back sooner rather then later.

@nathanhammond you most likely will need this soon, should we delete it for now then resurrect when we need?

**Comment by eventualbuddha** [comment]
@stefanpenner we could add it again in a 6.1 release. I think it'd be better to have a 6.0 with all of its features working than either a broken 6.0 or no 6.0 at all.

**Comment by rwjblue** [comment]
I explain how to make it work in https://github.com/babel/broccoli-babel-transpiler/issues/53

**Comment by Turbo87** [comment]
@stefanpenner I tend to agree with @eventualbuddha that we should probably just remove it for a first 6.0 release and then work to get it back in for e.g. another 6.1 release

**Pull request merged**
