### PR TITLE
Update dependencies and babel (6)

### PR DESCRIPTION
**Pull request by topaxi**
Updates all dependencies and babel to 6

### CODE REVIEW

**Comment by topaxi** [comment]
This PR depends on https://github.com/stefanpenner/hash-for-dep/issues/22 being fixed.

**Comment by topaxi** [comment]
I just noticed, that this module tries to include the browser polyfill if `options.browserPolyfill` is truthy.

Shall I include this functionality via the `babel-polyfill` module or should I remove it completely?

With the modular design of Babel 6, I'm not sure if this should still be handled in this module anymore.

It should be trivial to include the `babel-polyfill` in any broccoli build anyways

**Comment by maherbeg** [comment]
@topaxi I'd make it an option to pass through as long the version is updated! Thanks for taking this on, I was just about to do it.

**Comment by maherbeg** [comment]
Fixes https://github.com/babel/broccoli-babel-transpiler/issues/62

**Comment by shaunc** [comment]
@topaxi -- I obviously should have checked for your work before I tried to role my own (#73). The failure seen should go through. I think you need to fix the "named module" and "moduleID - true" tests by including `plugins: ["transform-es2015-modules-amd"]` rather than the `modules` option. (see [this commit](https://github.com/shaunc/broccoli-babel-transpiler/commit/8e5727101f79343d185966470481737177dc0751))... I'll close out mine if you are still pushing this.

**Comment by topaxi** [comment]
@shaunc I'm not sure what you mean, I'm not using the `modules` option anymore?

**Comment by topaxi** [comment]
The build seems to be failing for windows, maybe Babel 6 supports windows newlines and #58 can be reverted?
I have no windows machine to test this so I'm hesitating on changing and pushing this randomly.

**Comment by Turbo87** [comment]
@topaxi can you rebase on `master`?

**Comment by topaxi** [comment]
Rebased and green! :tada:

**Comment by Turbo87** [comment]
awesome!

@stefanpenner can you have a look at this once you're done in Switzerland?

**Comment by amercier** [comment]
@topaxi Tried this on one of my project, and this it seems to be working as expected. Good work! Looking forward for this to be merged!

**Comment by maherbeg** [comment]
@Turbo87 Anything we can do to get this merged in?

**Comment by Turbo87** [comment]
Okay, so the way forward from my perspective would be:

- create a 5.x branch for bugfixes on the old version
- merge this PR into master 
- release 6.0.0-alpha.1
- see how ember-cli-babel handles the new version 

@stefanpenner any objections?

**Comment by shaunc** [comment]
+1 :)

**Comment by stefanpenner** [comment]
> @stefanpenner any objections?

sounds perfect

**Comment by Turbo87** [comment]
@topaxi it seems like master has a failing test now after merging this. could you have a look at what might be causing this?

**Comment by Turbo87** [comment]
@stefanpenner could you add me to https://www.npmjs.com/package/broccoli-babel-transpiler/ so that I can release 6.0.0-alpha.1?

**Comment by stefanpenner** [comment]
➜  ~ npm owner add turbo87  broccoli-babel-transpiler
+ turbo87 (broccoli-babel-transpiler)

**Comment by Turbo87** [comment]
[v6.0.0-alpha.1](https://github.com/babel/broccoli-babel-transpiler/releases/tag/v6.0.0-alpha.1) released!   🎉

**Pull request merged**
